spring.thymeleaf.cache=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.com.acadconf=WARN
logging.level.org.springframework.security=WARN
app.upload.dir=${UPLOAD_DIR:/tmp/uploads/}
